theme: jekyll-theme-minimal
title: Bylaws of James River Outdoor Coalition
description: Find out more about us at jroc.net
logo: /assets/images/JROC-1101-Logo_FINAL-color_NOtag.png
show_downloads: true
collections:
  articles:
    output: true